# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under my_mlops_project/resources/*
# and my_mlops_project/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for my-mlops-project Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my_mlops_project

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  alex_prod:
    concurrency: my-mlops-project-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t alex_prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t alex_prod
