name: Feature and Training Integration Tests for my-mlops-project
on:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    working-directory: ./my_mlops_project/

env:
  DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

concurrency: my-mlops-project-feature-training-integration-test-staging

jobs:
  unit_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  integration_test:
    needs: unit_tests
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Test Deployment Target in Staging Workspace
        id: validate
        env: 
          DATABRICKS_TOKEN: ${{env.DATABRICKS_TOKEN}}
        run: |
          databricks bundle validate -t alex_test
      - name: Deploy Bundle to Test Deployment Target in Staging Workspace
        id: deploy
        env: 
          DATABRICKS_TOKEN: ${{env.DATABRICKS_TOKEN}}
        run: |
          databricks bundle deploy -t alex_test
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_engineering
        env: 
          DATABRICKS_TOKEN: ${{env.DATABRICKS_TOKEN}}
        run: |
          databricks bundle run write_feature_table_job -t alex_test
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        env: 
          DATABRICKS_TOKEN: ${{env.DATABRICKS_TOKEN}}
        run: |
          databricks bundle run model_training_job -t alex_test
